"""
database.py - SQLite helpers for RAIL-SENSE
Multi-Component LHB Bogie AI Diagnostic System
"""

# Import the sqlite3 module for interacting with SQLite databases
import sqlite3
# Import the os module for interacting with the operating system, like reading env variables
import os
# Import the json module for parsing and creating JSON strings
import json
# Import datetime to timestamp database entries
from datetime import datetime

# Read the database path from the environment variable 'DB_PATH', default to 'backend/railsense.db'
DB_PATH = os.getenv("DB_PATH", "backend/railsense.db")

# All 6 LHB bogie components: key = API name, value = folder name under dataset root
# Dictionary mapping internal component names to folder names in the dataset directory structure
# This helps the application know where to find images for each component type
COMPONENT_REGISTRY = {
    "coupler":    "cbc_image",
    "axle_box":   "axle_box",
    "brake_disk": "brake_disk",
    "damper":     "damper",
    "spring":     "spring",
    "wheel":      "wheel",
}

# Dictionary mapping internal component names to user-friendly, human-readable labels
# Used primarily for displaying component names in the frontend or reports
COMPONENT_LABELS = {
    "coupler":    "CBC Coupler",
    "axle_box":   "Axle Box",
    "brake_disk": "Brake Disk",
    "damper":     "Damper",
    "spring":     "Coil Spring",
    "wheel":      "Wheel",
}


def get_connection():
    """Establish and return a connection to the SQLite database."""
    # Connect to the SQLite database file specified by DB_PATH
    conn = sqlite3.connect(DB_PATH)
    # Configure the connection to return rows that act like dictionaries (can access by column name)
    conn.row_factory = sqlite3.Row
    # Return the configured connection object
    return conn


def init_db():
    """Create all required tables if they do not exist."""
    # Ensure the directory for the database file exists, create it if it doesn't
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    # Get a database connection
    conn = get_connection()
    # Create a cursor object to execute SQL commands
    cur  = conn.cursor()

    # ── inspections table ────────────────────────────────────
    # Execute SQL to create the 'inspections' table if it hasn't been created yet
    cur.execute("""
        CREATE TABLE IF NOT EXISTS inspections (
            id              INTEGER PRIMARY KEY AUTOINCREMENT, -- Unique auto-incrementing ID for the inspection
            created_at      TEXT NOT NULL,                     -- Timestamp of when the inspection was created
            component_type  TEXT DEFAULT 'coupler',            -- The type of component inspected (e.g., axle_box)
            coach_number    TEXT,                              -- Identifier for the coach
            coach_type      TEXT,                              -- Type/class of the coach
            depot           TEXT,                              -- Name of the depot where inspection took place
            zone            TEXT,                              -- Railway zone
            inspector_name  TEXT,                              -- Name of the person performing the inspection
            image_path      TEXT,                              -- Path to the uploaded/captured image of the component
            status          TEXT,                              -- Overall status (e.g., FIT, UNFIT, MONITOR)
            confidence      REAL,                              -- AI model's confidence score
            defect_score    REAL,                              -- Severity score of the detected defect
            rust_level      REAL,                              -- Quantified rust level on the component
            alignment_ok    INTEGER,                           -- Boolean flag (1=True, 0=False) indicating alignment
            bbox_json       TEXT,                              -- JSON string of bounding boxes for detected regions
            ai_model        TEXT,                              -- Name of the AI model used for inference
            ai_diagnosis    TEXT,                              -- Textual diagnosis from the AI
            ai_checklist    TEXT,                              -- JSON string representing checklist results
            ai_action       TEXT,                              -- Recommended action generated by the AI
            notes           TEXT                               -- Additional manual notes from the inspector
        )
    """)
    # Commit the transaction to save the table creation
    conn.commit()

    # Migrate inspections: add component_type if it came from old schema
    try:
        # Attempt to add the 'component_type' column to handle older versions of the database
        cur.execute("ALTER TABLE inspections ADD COLUMN component_type TEXT DEFAULT 'coupler'")
        # Commit the alteration
        conn.commit()
        # Log successful migration
        print("[DB] Migrated inspections: added component_type column.")
    except Exception:
        # Ignore errors if the column already exists
        pass  # column already exists

    # ── dataset_index table — recreate if schema is stale ────
    # Check if the 'component' column exists (old schema used different names)
    # Use PRAGMA table_info to get column details of the 'dataset_index' table
    cur.execute("PRAGMA table_info(dataset_index)")
    # Extract just the column names (index 1 of the returned tuples)
    cols = [row[1] for row in cur.fetchall()]
    # If the table exists but lacks the new 'component' column, it's stale
    if cols and "component" not in cols:
        # Old schema — drop the stale table
        cur.execute("DROP TABLE dataset_index")
        # Commit the drop
        conn.commit()
        # Log the drop action
        print("[DB] Dropped stale dataset_index table — will recreate.")
        # Clear the cols list to force recreation below
        cols = []  # force create below

    # If cols is empty (table didn't exist or was just dropped), create it
    if not cols:
        # Execute SQL to create the 'dataset_index' table
        cur.execute("""
            CREATE TABLE dataset_index (
                id          INTEGER PRIMARY KEY AUTOINCREMENT, -- Unique ID for the dataset entry
                component   TEXT NOT NULL,                     -- Type of the component (e.g., wheel)
                label       TEXT NOT NULL,                     -- Label/class of the image (e.g., normal, defect)
                filename    TEXT NOT NULL,                     -- Name of the image file
                filepath    TEXT NOT NULL                      -- Full relative path to the image file
            )
        """)
        # Commit the table creation
        conn.commit()
        # Log the table creation
        print("[DB] Created dataset_index table.")

    # Close the database connection
    conn.close()
    # Log successful initialization
    print("[DB] Tables initialised (multi-component schema).")


def save_inspection(data: dict) -> int:
    """Insert a new inspection record into the database and return its ID."""
    # Get a database connection
    conn = get_connection()
    # Create a cursor object
    cur  = conn.cursor()
    # Execute the INSERT statement
    cur.execute(
        """
        INSERT INTO inspections
            (created_at, component_type, coach_number, coach_type, depot, zone, inspector_name,
             image_path, status, confidence, defect_score, rust_level,
             alignment_ok, bbox_json, ai_model, ai_diagnosis, ai_checklist, ai_action, notes)
        VALUES
            (:created_at, :component_type, :coach_number, :coach_type, :depot, :zone, :inspector_name,
             :image_path, :status, :confidence, :defect_score, :rust_level,
             :alignment_ok, :bbox_json, :ai_model, :ai_diagnosis, :ai_checklist, :ai_action, :notes)
        """,
        {
            # Bind parameters with fallback default values if keys are missing from the data dict
            "created_at":     data.get("created_at", datetime.now().isoformat()), # Default to current time
            "component_type": data.get("component_type", "coupler"),              # Default component is coupler
            "coach_number":   data.get("coach_number", ""),                       # Default empty string
            "coach_type":     data.get("coach_type", ""),                         # Default empty string
            "depot":          data.get("depot", ""),                              # Default empty string
            "zone":           data.get("zone", ""),                               # Default empty string
            "inspector_name": data.get("inspector_name", ""),                     # Default empty string
            "image_path":     data.get("image_path", ""),                         # Default empty string
            "status":         data.get("status", "UNKNOWN"),                      # Default status UNKNOWN
            "confidence":     data.get("confidence", 0.0),                        # Default confidence 0.0
            "defect_score":   data.get("defect_score", 0.0),                      # Default defect score 0.0
            "rust_level":     data.get("rust_level", 0.0),                        # Default rust level 0.0
            "alignment_ok":   1 if data.get("alignment_ok", True) else 0,         # Convert boolean to integer 1/0
            "bbox_json":      json.dumps(data.get("bbox")) if data.get("bbox") else None, # Serialize bbox dict to JSON
            "ai_model":       data.get("ai_model", ""),                           # Default empty string
            "ai_diagnosis":   data.get("ai_diagnosis", ""),                       # Default empty string
            "ai_checklist":   json.dumps(data.get("ai_checklist", {})),           # Serialize checklist dict to JSON
            "ai_action":      data.get("ai_action", ""),                          # Default empty string
            "notes":          data.get("notes", ""),                              # Default empty string
        },
    )
    # Get the auto-generated ID of the newly inserted row
    new_id = cur.lastrowid
    # Commit the insert transaction
    conn.commit()
    # Close the connection
    conn.close()
    # Return the new row ID
    return new_id


def _decode_row(r: dict) -> dict:
    """Helper function to parse JSON strings back into Python dictionaries for a database row."""
    # Check if 'bbox_json' exists and is not empty
    if r.get("bbox_json"):
        try:
            # Attempt to parse the JSON string into a Python object and store in 'bbox'
            r["bbox"] = json.loads(r["bbox_json"])
        except Exception:
            # If parsing fails, set 'bbox' to None
            r["bbox"] = None
    # Check if 'ai_checklist' exists and is not empty
    if r.get("ai_checklist"):
        try:
            # Attempt to parse the JSON string back into the 'ai_checklist' key
            r["ai_checklist"] = json.loads(r["ai_checklist"])
        except Exception:
            # Ignore parsing errors, leave as is
            pass
    # Return the modified dictionary
    return r


def get_all_inspections(limit: int = 100, component: str = None) -> list:
    """Retrieve a list of most recent inspections, optionally filtered by component type."""
    # Get a database connection
    conn = get_connection()
    # Create a cursor object
    cur  = conn.cursor()
    # If a specific component filter is provided
    if component:
        # Query inspections matching the component type, ordered newest first
        cur.execute(
            "SELECT * FROM inspections WHERE component_type=? ORDER BY id DESC LIMIT ?",
            (component, limit),
        )
    else:
        # Otherwise, query all inspections, ordered newest first
        cur.execute("SELECT * FROM inspections ORDER BY id DESC LIMIT ?", (limit,))
    # Fetch all results, convert them to dicts, and decode JSON fields using _decode_row
    rows = [_decode_row(dict(r)) for r in cur.fetchall()]
    # Close the database connection
    conn.close()
    # Return the list of decoded rows
    return rows


def get_inspection_by_id(inspection_id: int):
    """Retrieve a single inspection record by its primary key ID."""
    # Get a database connection
    conn = get_connection()
    # Create a cursor object
    cur  = conn.cursor()
    # Query for the specific inspection ID
    cur.execute("SELECT * FROM inspections WHERE id = ?", (inspection_id,))
    # Fetch the single matching row
    row  = cur.fetchone()
    # Close the database connection
    conn.close()
    # If no row was found, return None
    if not row:
        return None
    # Convert row to dict and decode JSON fields, then return
    return _decode_row(dict(row))


def index_dataset(dataset_root: str):
    """
    Scan all component folders under dataset_root and populate dataset_index.
    Structure: dataset_root/<folder_name>/{normal,defect}/
    """
    # Get a database connection
    conn  = get_connection()
    # Create a cursor object
    cur   = conn.cursor()
    # Clear out the old index completely before re-indexing
    cur.execute("DELETE FROM dataset_index")
    # Initialize a counter for total images indexed
    total = 0

    # Iterate over every component and its corresponding folder name
    for component, folder_name in COMPONENT_REGISTRY.items():
        # Construct the full path to the component's folder
        component_path = os.path.join(dataset_root, folder_name)
        # Check both 'normal' and 'defect' label subfolders
        for label in ("normal", "defect"):
            # Construct the path to the specific label folder
            label_path = os.path.join(component_path, label)
            # If the directory doesn't exist, skip to the next
            if not os.path.isdir(label_path):
                continue
            # Iterate over all files in the label folder, sorted alphabetically
            for fname in sorted(os.listdir(label_path)):
                # Process only files with known image extensions (case-insensitive)
                if fname.lower().endswith((".jpg", ".jpeg", ".png", ".webp")):
                    # Construct the relative file path and normalize slashes for consistency
                    fpath = os.path.join(label_path, fname).replace("\\", "/")
                    # Insert the image information into the dataset_index table
                    cur.execute(
                        "INSERT INTO dataset_index (component, label, filename, filepath) VALUES (?, ?, ?, ?)",
                        (component, label, fname, fpath),
                    )
                    # Increment the counter
                    total += 1

    # Commit all the insertions
    conn.commit()
    # Close the database connection
    conn.close()
    # Log the total number of indexed images
    print(f"[DB] Indexed {total} images across {len(COMPONENT_REGISTRY)} components.")


def get_dataset_images(component: str = None, label: str = None) -> list:
    """Retrieve dataset images, optionally filtered by component and/or label."""
    # Get a database connection
    conn       = get_connection()
    # Create a cursor object
    cur        = conn.cursor()
    # List to hold WHERE clause fragments
    conditions = []
    # List to hold parameter values for the query
    params     = []
    # If filtering by component, add condition and parameter
    if component:
        conditions.append("component=?")
        params.append(component)
    # If filtering by label, add condition and parameter
    if label:
        conditions.append("label=?")
        params.append(label)
    # Construct the full WHERE clause if there are any conditions
    where = f"WHERE {' AND '.join(conditions)}" if conditions else ""
    # Execute the query with the dynamically built WHERE clause, ordering the results nicely
    cur.execute(
        f"SELECT * FROM dataset_index {where} ORDER BY component, label, filename",
        params,
    )
    # Fetch all matching rows and convert them to dictionaries
    rows = [dict(r) for r in cur.fetchall()]
    # Close the database connection
    conn.close()
    # Return the list of image records
    return rows


def get_stats() -> dict:
    """Aggregate and return statistics for both inspections and dataset indices."""
    # Get a database connection
    conn = get_connection()
    # Create a cursor object
    cur  = conn.cursor()

    # Query the total number of inspections
    cur.execute("SELECT COUNT(*) as total FROM inspections")
    total = cur.fetchone()["total"]
    
    # Query the count of 'FIT' inspections
    cur.execute("SELECT COUNT(*) as c FROM inspections WHERE status='FIT'")
    fit = cur.fetchone()["c"]
    
    # Query the count of 'UNFIT' inspections
    cur.execute("SELECT COUNT(*) as c FROM inspections WHERE status='UNFIT'")
    unfit = cur.fetchone()["c"]
    
    # Query the count of 'MONITOR' inspections
    cur.execute("SELECT COUNT(*) as c FROM inspections WHERE status='MONITOR'")
    monitor = cur.fetchone()["c"]
    
    # Query the average AI confidence score across all inspections
    cur.execute("SELECT AVG(confidence) as avg FROM inspections")
    # If no records exist, avg might be None, so fallback to 0.0
    avg_conf = cur.fetchone()["avg"] or 0.0

    # Per-component inspection breakdown
    # Group the inspections by component type and status, getting counts for each pair
    cur.execute(
        "SELECT component_type, status, COUNT(*) as cnt FROM inspections GROUP BY component_type, status"
    )
    # Dictionary to store the stats per component
    component_stats: dict = {}
    for row in cur.fetchall():
        # Get the component type, default to 'coupler' if missing
        comp = row["component_type"] or "coupler"
        # Initialize the component dictionary if it doesn't exist yet
        if comp not in component_stats:
            component_stats[comp] = {"FIT": 0, "UNFIT": 0, "MONITOR": 0, "total": 0}
        # Add the count for the specific status
        component_stats[comp][row["status"]] = row["cnt"]
        # Also add to the total for this component
        component_stats[comp]["total"] += row["cnt"]

    # Per-component dataset image counts
    # Group the dataset images by component and label, getting counts for each pair
    cur.execute(
        "SELECT component, label, COUNT(*) as cnt FROM dataset_index GROUP BY component, label"
    )
    # Dictionary to store the dataset counts per component
    dataset_counts: dict = {}
    for row in cur.fetchall():
        comp = row["component"]
        # Initialize the dataset count dictionary for this component if needed
        if comp not in dataset_counts:
            dataset_counts[comp] = {"normal": 0, "defect": 0, "total": 0}
        # Add the count for the specific label (normal/defect)
        dataset_counts[comp][row["label"]] = row["cnt"]
        # Also add to the overall total for this component
        dataset_counts[comp]["total"] += row["cnt"]

    # Close the database connection
    conn.close()
    
    # Construct and return the final dictionary containing all collected statistics
    return {
        "total":           total,
        "fit":             fit,
        "unfit":           unfit,
        "monitor":         monitor,
        "avg_confidence":  round(avg_conf, 3), # Round the average confidence to 3 decimal places
        "component_stats": component_stats,
        "dataset_counts":  dataset_counts,
    }
